### ISSUE TITLE
Auto SNI

### ISSUE THREAD

**Issue by jschlyter** [kirei/sslyze#16]
It would be most useful with an option to set SNI automagically to the hostname that is used to connect (i.e., so one can scan multiple hosts with SNI)

**Comment by trams242** [comment]
Example: connecting to www.dn.se should if SNI=auto let --SNI=www.dn.se

**Comment by secworks** [comment]
It is a good suggestion. I will try and add it.

**Comment by secworks** [comment]
Committed to master in https://github.com/kirei/sslyze/commit/0f667b81352eba66d06fcefcea821ad555d88551
